# Pre-commit hooks configuration
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: debug-statements

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.13
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]


-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
    -   id: gitleaks

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

# -   repo: local
#     hooks:
#     -   id: pytest-check
#         name: pytest-check
#         entry: pytest
#         language: system
#         pass_filenames: false
#         always_run: true
#         args: [
#             "tests/",
#             "-xvs"
#         ]
