name: Connect to Tailscale Network

on:
  workflow_dispatch:  # Manual trigger for testing
  # You can add other triggers later (push, etc.)

jobs:
  connect-to-tailnet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: tag:github-actions
          hostname: github-actions-runner

      - name: Diagnose Network Connectivity
        run: |
          # Display Tailscale IP
          echo "My Tailscale IP is: $(tailscale ip -4)"

          # Check if Tailscale is running
          tailscale status

          # Show the routing table
          ip route

          # Try pinging your webhook server
          #ping -c 4 100.70.24.24

          # Verbose curl to see where it's failing
          curl -v http://100.70.24.24:8000/health

      # - name: Test Tailscale Connection
      #   run: |
      #     # Display Tailscale IP
      #     echo "My Tailscale IP is: $(tailscale ip -4)"

      #     # Ping your webhook server to test connectivity
      #     # ping -c 4 100.70.24.24

      #     echo "Test webhook connection..."
      #     # Test webhook (replace with your actual webhook endpoint)
      #     curl -s -X POST \
      #       http://100.70.24.24:8000/deploy \
      #       -H "Content-Type: application/json" \
      #       -d '{"test": "connectivity", "source": "github-actions"}'
      #     echo "Webhook test completed."
